import Head from "next/head";
import Image from "next/image"
import { api } from "@/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import type { NextPage } from "next";
import { useState } from "react";

const CreateLinkWizard = () => {
  const { user } = useUser();

  const [title, setTitle] = useState('')
  const [url, setUrl] = useState('')
  const [category, setCategory] = useState('null')


  const { mutate } = api.links.create.useMutation()

  const handleSubmit = () => mutate({
    title,
    url,
    category
  })

  if (!user) return null;

  return <div className="flex gap-3">
    <Image alt="Profile picture" src={user.imageUrl} width={56} height={56} className="rounded-full h-14 w-14" />
    <input type="text" placeholder="Enter headline" className="border-2 border-black/50 rounded p-4" value={title} onChange={(e) => setTitle(e.target.value)} />

    <input type="text" placeholder="Enter link url" className="border-2 border-black/50 rounded p-4" value={url} onChange={(e) => setUrl(e.target.value)} />

    <select onChange={(e) => setCategory(e.target.value)} value={category}>
      <option value="reddit">Reddit</option>
      <option value="instagram">Instagram</option>
      <option value="twitter">Twitter</option>
      <option value="tiktok">Tiktok</option>
      <option value="threads">threads</option>
      <option value="facebook">facebook</option>
    </select>
    <button onClick={handleSubmit}>Add Link</button>
  </div>
}



const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.links.getAll.useQuery()

  return (
    <>
      <Head>
        <title>myso.xyz - Your socials all in one place</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          {!user.isSignedIn && (
            <div className="text-3xl border-2 hover:bg-white hover:text-black hover:border-black/75 rounded p-7 bg-black text-white">
              <SignInButton />
            </div>
          )}
          {!!user.isSignedIn && (
            <>
              <CreateLinkWizard />
              <div className="text-3xl border-2 hover:bg-white hover:text-black hover:border-black/75 rounded p-7 bg-black text-white">
                <SignOutButton />
              </div>
            </>
          )}
        </div>

        <h3>Links</h3>
        {data?.map(({ link, user }) => (

          <div key={link.id} >
            <Image src={user.imageUrl} width={40} height={40} alt="Profile picture" />
            <a key={link.id} href={link.url}>{link.title}</a>
          </div>
        ))}
      </main>
    </>
  );
}

export default Home;