import Head from "next/head";
import Image from "next/image"
import { api } from "@/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import type { NextPage } from "next";

const CreateLinkWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return <div className="flex gap-3">
    <Image alt="Profile picture" src={user.imageUrl} width={56} height={56} className="rounded-full h-14 w-14" />
    <input type="text" id="displayName" placeholder="Claim username" className="border-2 border-black/50 rounded p-4" />
  </div>
}



const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.links.getAll.useQuery()

  return (
    <>
      <Head>
        <title>myso.xyz - Your socials all in one place</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          {!user.isSignedIn && (
            <div className="text-3xl border-2 hover:bg-white hover:text-black hover:border-black/75 rounded p-7 bg-black text-white">
              <SignInButton />
            </div>
          )}
          {!!user.isSignedIn && (
            <>
              <CreateLinkWizard />
              <div className="text-3xl border-2 hover:bg-white hover:text-black hover:border-black/75 rounded p-7 bg-black text-white">
                <SignOutButton />
              </div>
            </>
          )}
        </div>

        <h3>Links</h3>
        {data?.map(link => (
          <a key={link.id} href={link.url}>{link.title}</a>
        ))}
      </main>
    </>
  );
}

export default Home;