import Head from "next/head";
import Image from "next/image"
import { api } from "@/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import type { NextPage } from "next";
import { useState } from "react";

const ClaimDisplayName = () => {
  const [ displayName, setDisplayName ] = useState('')
  const submitClaim = () => {
    console.log(displayName)
  }
  return (
    <div>
      <input  className="border-2 border-slate-800/80 rounded mr-4 p-3" type="text" placeholder="Your Display Name Here" onChange={(evt) => setDisplayName(evt.target.value)}/>
      <button  className="border-2 border-slate-800/80 rounded p-3" onClick={submitClaim}>Claim</button>
    </div>
  )
}


const Home: NextPage = () => {
  const { isSignedIn, user } = useUser();
  return (
    <>
      <Head>
        <title>myso.xyz - Your socials all in one place</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          {!isSignedIn && (
            <div className="text-3xl border-2 hover:bg-white hover:text-black hover:border-black/75 rounded p-7 bg-black text-white">
              <SignInButton />

            </div>
          )}
          {!!isSignedIn && (
            <>
              <div className="text-3xl border-2 hover:bg-white hover:text-black hover:border-black/75 rounded p-7 bg-black text-white">
                <SignOutButton />
              </div>
            </>
          )}
        </div>
      </main>
    </>
  );
}

export default Home;